a={1,2.5,'hey','sup'}
#a.pop()
#a.clear()
#a.remove(2.5)
#a.discard('hey')
#a.add('noway')
#a.update([3,4.5,('okie')])
b={2.5,'hey',}
#print(a-b)
#print(b-a)
#print(a.union(b))
#print(b|a)
#print(b.intersection(a))
#print(a&b)
#print(b.issubset(a))
#print(a.issubset(b))
#print(a.issuperset(b))
#print(b.issuperset(a))
c={'woah','hehehe',9.7589}
d={'lol',9786}
#print(c.isdisjoint(d))
#print(d.isdisjoint(c))